(()=>{
 const site=document.body.dataset.site||'artist';
 const header=document.querySelector('header');if(!header)return;
 const button=document.createElement('button');button.type='button';button.className='theme-toggle';
 const set=mode=>{document.documentElement.dataset.theme=mode;button.textContent=mode==='dark'?'☀ Light mode':'◐ Dark mode';button.setAttribute('aria-label',mode==='dark'?'Switch to cream mode':'Switch to dark mode');button.setAttribute('aria-pressed',String(mode==='dark'));try{localStorage.setItem(`${site}-theme`,mode)}catch{}};
 let saved='light';try{saved=localStorage.getItem(`${site}-theme`)==='dark'?'dark':'light'}catch{}set(saved);
 button.addEventListener('click',()=>set(document.documentElement.dataset.theme==='dark'?'light':'dark'));
 const cart=document.createElement('a');cart.className='site-cart rr-cart-icon';cart.href='https://console.richrowmusic.com/addons/cart';cart.setAttribute('aria-label','Shopping cart');cart.innerHTML='<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M2 3h2l2.2 11.5a2 2 0 0 0 2 1.6h10.3a2 2 0 0 0 2-1.6L22 7H5"/></svg>';
 header.append(cart,button);
})();

// Keep the first three pages visible. The remaining links form a disclosure.
(()=>{const nav=document.querySelector('header nav');if(!nav||nav.dataset.compact)return;if(!nav.querySelector('a[href="login.html"]')){const signIn=document.createElement('a');signIn.href='login.html';signIn.textContent='Sign In / Register';nav.append(signIn);}const links=[...nav.children].filter(e=>e.tagName==='A');if(links.length<=3)return;nav.dataset.compact='true';nav.classList.add('compact-nav');const wrap=document.createElement('div');wrap.className='nav-disclosure';const toggle=document.createElement('button');toggle.type='button';toggle.className='nav-toggle';toggle.setAttribute('aria-label','Open more pages');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','more-pages');toggle.innerHTML='<span aria-hidden="true">☰</span><span>More</span>';const panel=document.createElement('div');panel.id='more-pages';panel.className='nav-panel';panel.hidden=true;for(const a of links.slice(3))panel.append(a);wrap.append(toggle,panel);nav.append(wrap);const set=open=>{panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close more pages':'Open more pages');};toggle.onclick=()=>set(panel.hidden);nav.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){set(false);toggle.focus();}});document.addEventListener('click',e=>{if(!wrap.contains(e.target))set(false);});panel.addEventListener('click',e=>{if(e.target.closest('a'))set(false);});})();

// Homepage live takeover: it occupies no space while offline or unavailable.
(()=>{
 if(!['/','/index.html'].includes(location.pathname))return;
 const sites={'richrowmusic.com':'richrow','waynekastro.com':'waynekastro','dracodon17.com':'dracodon17','goldenrama440.com':'goldenrama440'};
 const site=sites[location.hostname.replace(/^www\./,'')];if(!site)return;
 const main=document.querySelector('main');if(!main)return;const sdkReady=new Promise(resolve=>{if(window.PlayerSdk)return resolve();const script=document.createElement('script');script.src=site==='richrow'?'/assets/api-video-player.js':'/api-video-player.js';script.onload=resolve;script.onerror=resolve;document.head.append(script);});
 const section=document.createElement('section');section.id='rr-home-live';section.hidden=true;section.setAttribute('aria-label','Live now');
 section.style.cssText='margin:32px 0;padding:24px;border:1px solid #b99a61;border-radius:20px;background:var(--panel,transparent)';
 (main.querySelector('.hero')||main.firstElementChild)?.after(section);
 let current='',players=[],timers=[];const clearPlayers=()=>{players.forEach(p=>p.destroy());players=[];timers.forEach(clearInterval);timers=[];};
 async function refresh(){if(document.hidden){section.hidden=true;return;}try{
  const response=await fetch('https://console.richrowmusic.com/api/addon/portal/live-now?site='+site,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const sessions=await response.json();if(!Array.isArray(sessions)||!sessions.length){section.hidden=true;clearPlayers();section.replaceChildren();current='';return;}
  const key=JSON.stringify(sessions.map(({player_url,...rest})=>({...rest,has_player:!!player_url})));if(key!==current){clearPlayers();section.replaceChildren();for(const live of sessions){const card=document.createElement('article'),badge=document.createElement('p'),title=document.createElement('h2'),description=document.createElement('p'),link=document.createElement('a');badge.textContent='● LIVE NOW · '+live.artist;badge.style.color='#b99a61';title.textContent=live.title;description.textContent=live.description||'';link.textContent='Watch, chat & support';link.href='https://console.richrowmusic.com/addons/portal?site='+encodeURIComponent(live.site)+'&watch='+encodeURIComponent(live.id);link.className='btn';card.append(badge,title,description);if(live.player_url){const u=new URL(live.player_url);if(u.origin==='https://embed.api.video'){const frame=document.createElement('iframe');frame.src=u.href;frame.title=live.title;frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.style.cssText='display:block;width:100%;aspect-ratio:16/9;border:0;border-radius:12px;margin:16px 0';card.append(frame);sdkReady.then(()=>{if(!frame.isConnected||!window.PlayerSdk)return;const p=new window.PlayerSdk(frame);players.push(p);let playing=false,session;p.addEventListener('play',()=>playing=true);p.addEventListener('pause',()=>playing=false);p.addEventListener('ended',()=>playing=false);p.addEventListener('error',()=>playing=false);timers.push(setInterval(async()=>{if(!playing||document.hidden)return;try{const response=await fetch('https://console.richrowmusic.com/api/addon/portal/heartbeat',{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({id:live.id,session})});const result=await response.json();if(response.ok)session=result.session;}catch{}},15000));});}}card.append(link);section.append(card);}current=key;}section.hidden=false;
 }catch{section.hidden=true;clearPlayers();section.replaceChildren();current='';}}
 refresh();setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);
})();

(()=>{const site=({'richrowmusic.com':'richrow','waynekastro.com':'waynekastro','dracodon17.com':'dracodon17','goldenrama440.com':'goldenrama440'})[location.hostname.replace(/^www\./,'')];if(!site)return;let visit;try{visit=sessionStorage.getItem('rr_stats_visit')||crypto.randomUUID();sessionStorage.setItem('rr_stats_visit',visit);}catch{visit=crypto.randomUUID();}const track=(kind,stream_id)=>fetch('https://console.richrowmusic.com/api/addon/portal/track',{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({site,kind,visit,stream_id:stream_id||null}),keepalive:true}).catch(()=>{});track('page_view');document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;try{const u=new URL(a.href);if(u.searchParams.has('watch')||/live\.html$/.test(u.pathname))track('live_click',u.searchParams.get('watch'));else if(/support\.html$/.test(u.pathname)||u.searchParams.get('support')==='open')track('donate_click');}catch{}});})();
