const STREAM='https://richrow-radio.129-213-164-255.sslip.io/listen/rich_row_radio/radio.mp3';
export function mountSpeakerRadio(root){
 root.setAttribute('aria-label','Highlife Radio live player');
 root.style.cssText='display:block!important;margin:18px 0!important;padding:0!important;border:0!important;background:transparent!important';
 root.replaceChildren();
 const shadow=root.attachShadow({mode:'open'});
 shadow.innerHTML=`<style>
 :host{display:block}*{box-sizing:border-box}.player{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:10px 28px;background:#11110f;border:1px solid #786239;border-radius:18px;color:#fff;font-family:Arial,sans-serif;overflow:hidden}.copy{flex:1;min-width:0}.eyebrow{font-size:10px;letter-spacing:2px;color:#dec389;text-transform:uppercase;margin:0 0 8px}.title{font-size:24px;font-weight:800;margin:0 0 8px;line-height:1.1}.prompt{font-size:15px;line-height:1.5;margin:0;color:#eee}.status{font-size:12px;color:#dec389;min-height:18px;margin:8px 0}.more{font-size:12px;color:#dec389;text-underline-offset:4px}.radio{position:relative;width:340px;max-width:100%;flex-shrink:0;aspect-ratio:3/2}.radio img{display:block;width:100%;height:100%;object-fit:contain;border-radius:12px}.speaker[aria-pressed=false]{background:transparent;border-color:transparent;box-shadow:none}.speaker[aria-pressed=false] svg{visibility:hidden}.speaker[aria-pressed=false]:hover{background:#ffe2a012;box-shadow:0 0 18px #f6c66444}.speaker{position:absolute;left:79.4%;top:54%;transform:translate(-50%,-50%);width:29%;aspect-ratio:1;border:2px solid #f1d08b;border-radius:50%;background:radial-gradient(circle at 36% 25%,#393630,#15130f 65%,#080706);color:#ffe2a0;display:grid;place-items:center;cursor:pointer;box-shadow:inset 0 4px 4px #fff4,inset 0 -7px 7px #000,0 0 0 4px #ad8241,0 0 0 7px #463017,0 7px 0 6px #171009,0 12px 18px #000b;transition:background .2s,box-shadow .2s}.speaker:hover{background:#715523dd;box-shadow:0 0 0 6px #e4c58144,0 0 22px #f6c66466}.speaker:focus-visible{outline:3px solid white;outline-offset:6px}.speaker svg{width:44%;height:44%;fill:url(#gold-button);filter:drop-shadow(0 1px 0 #8a6124) drop-shadow(0 2px 0 #8a6124) drop-shadow(0 3px 0 #8a6124) drop-shadow(0 5px 2px #000);}.speaker[aria-pressed=true]{box-shadow:0 0 0 5px #e4c58144,0 0 20px #f6c66455}.volume{display:flex;gap:8px;align-items:center;font-size:11px;color:#d4c6aa;margin:10px 0 0}.volume input{width:100px;accent-color:#dec389}audio{display:none}@media(max-width:640px){.player{flex-direction:column;gap:0;padding:18px 16px 6px}.copy{width:100%;text-align:center}.title{font-size:22px}.prompt{font-size:14px}.radio{width:300px}.volume{justify-content:center}.status{margin:4px 0}.eyebrow{margin-bottom:6px}}@media(prefers-reduced-motion:reduce){.speaker{transition:none}}
 .player{flex-direction:column;gap:0;padding:0;background:transparent;border:0;border-radius:0;overflow:visible}.radio{order:1;width:360px}.copy{order:2;flex:0;width:100%;text-align:center;color:inherit}.eyebrow{display:none}.prompt{font-size:13px;color:inherit}.status{font-size:11px;color:inherit;margin:3px 0}.volume{display:inline-flex;margin:6px 0 0 12px;color:inherit}.more{color:inherit;font-size:11px}:host{color:inherit}.player{color:inherit}@media(max-width:640px){.player{padding:0}.radio{width:300px}.copy{text-align:center}.prompt{font-size:12px}.volume{margin-left:10px}}</style><div class="player"><div class="copy"><p class="eyebrow">Live radio</p><p class="prompt">Press the gold speaker button to listen.</p><p class="status" role="status" aria-live="polite">Ready when you are.</p><a class="more" href="https://richrowmusic.com/radio.html" target="_blank" rel="noopener">Full radio player ↗</a><label class="volume">Volume <input aria-label="Radio volume" type="range" min="0" max="1" step="0.05" value="0.8"></label></div><div class="radio"><img alt="Black and gold portable radio" width="1536" height="1024"><button class="speaker" type="button" aria-label="Play Highlife Radio" aria-pressed="false" title="Play Highlife Radio"></button></div><audio preload="none"></audio></div>`;
 shadow.querySelector('img').src=new URL('./radio-branded.png',import.meta.url).href;
 const audio=shadow.querySelector('audio'),button=shadow.querySelector('button'),status=shadow.querySelector('.status');
 audio.src=STREAM;audio.volume=.8;
 const icon=playing=>`<svg viewBox="0 0 48 48" aria-hidden="true"><defs><linearGradient id="gold-button" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#fff6d1"/><stop offset="45%" stop-color="#e7bf6b"/><stop offset="100%" stop-color="#b7802c"/></linearGradient></defs>${playing?'<path d="M12 8h9v32h-9zm15 0h9v32h-9z"/>':'<path d="M15 7v34l28-17z"/>'}</svg>`;
 const update=()=>{const playing=!audio.paused;button.innerHTML=icon(playing);button.setAttribute('aria-pressed',String(playing));button.setAttribute('aria-label',(playing?'Pause':'Play')+' Highlife Radio');button.title=(playing?'Pause':'Play')+' Highlife Radio';};
 update();
 button.addEventListener('click',async()=>{if(!audio.paused){audio.pause();return;}status.textContent='Connecting to Highlife Radio…';audio.load();try{await audio.play();}catch(e){if(e.name!=='AbortError'){status.textContent='Unable to connect. Press the speaker to retry.';update();}}});
 audio.addEventListener('playing',()=>{status.textContent='You’re listening to Highlife Radio.';update();});
 audio.addEventListener('play',()=>{update();document.dispatchEvent(new CustomEvent('highlife-play',{detail:audio}));document.querySelectorAll('audio,video').forEach(other=>{if(other!==audio)other.pause();});});
 audio.addEventListener('pause',()=>{status.textContent='Paused. Press the speaker to listen live.';update();});
 audio.addEventListener('waiting',()=>{if(!audio.paused)status.textContent='Connecting to Highlife Radio…';});
 audio.addEventListener('error',()=>{audio.pause();status.textContent='Stream unavailable. Press the speaker to retry.';update();});
 document.addEventListener('highlife-play',event=>{if(event.detail!==audio)audio.pause();});
 document.addEventListener('play',event=>{if(event.target!==audio&&event.target instanceof HTMLMediaElement)audio.pause();},true);
 shadow.querySelector('input').addEventListener('input',e=>{audio.volume=Number(e.target.value);});
}
