'use strict';
const site=document.body.dataset.site,base='https://console.richrowmusic.com',content=document.querySelector('#content');
document.querySelector('#year').textContent=new Date().getFullYear();
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const safe=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}};
function link(url,label){const a=node('a',label,'action');a.href=safe(url)||base;a.rel='noopener noreferrer';a.target='_blank';return a;}
function block(b){const box=node('div',null,'block');if(b.title)box.append(node('h3',b.title));if(b.body)box.append(node('p',b.body));
 if(['button','distribution','instagram','tiktok','facebook','x'].includes(b.type)&&safe(b.url))box.append(link(b.url,b.label||'Open '+b.type+' ↗'));
 if(['image','cover','release'].includes(b.type)&&safe(b.media?.url)){const img=node('img');img.src=b.media.url;img.alt=b.title||b.media.name||'Artist photo';img.loading='lazy';box.append(img);}
 if(b.type==='gallery'){const grid=node('div',null,'gallery');for(const m of b.media||[]){if(!safe(m.url))continue;const img=node('img');img.src=m.url;img.alt=m.name||'Artist photo';img.loading='lazy';grid.append(img);}box.append(grid);}
 if(['audio','video'].includes(b.type)&&safe(b.media?.url)){const m=node(b.type);m.src=b.media.url;m.controls=true;m.preload='none';if(b.type==='video')m.playsInline=true;box.append(m);}
 if(['youtube','vimeo'].includes(b.type)&&safe(b.url)&&['www.youtube-nocookie.com','player.vimeo.com'].includes(new URL(b.url).hostname)){const frame=node('iframe');frame.src=b.url;frame.title=b.title||'Official video';frame.loading='lazy';frame.allow='fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';box.append(frame);}
 if(b.type==='release')box.append(node('p',b.artist),link(base+'/addons/store?product='+encodeURIComponent(b.productId),b.label||'View release'));
 if(b.type==='radio')box.append(link(base+'/addons/radio',b.label||'Listen to Highlife Radio'));
 if(b.type==='divider')box.append(node('hr'));if(b.type==='spacer')box.style.height=Math.min(160,Math.max(8,Number(b.height)||8))+'px';return box;}
async function load(){try{const r=await fetch(base+'/api/addon/page?slug='+encodeURIComponent(site),{credentials:'omit',cache:'no-store'});if(!r.ok)throw Error('unavailable');const p=await r.json();if(!Array.isArray(p.blocks))throw Error('invalid');const fragment=document.createDocumentFragment();let section,number=0;
 for(const [i,b] of p.blocks.filter(b=>!b.hidden).entries()){if(i===0&&b.type==='heading'){const h=document.querySelector('h1'),title=b.title||p.title;const lines=title==='DracoDon17'?['Draco','Don17.']:title==='Wayne Kastro'?['Wayne','Kastro.']:null;if(lines)h.replaceChildren(...lines.map(t=>node('span',t)));else{h.textContent=title;h.style.fontSize='clamp(48px,8vw,120px)';}document.querySelector('#intro').textContent=b.body||'';continue;}
 if(b.type==='heading'){section=node('section');section.id=(b.title||'section-'+number).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const head=node('div',null,'section-head');head.append(node('small',String(++number).padStart(2,'0')),node('h2',b.title));section.append(head);if(b.body)section.append(node('p',b.body));fragment.append(section);}else{if(!section){section=node('section');fragment.append(section);}section.append(block(b));}}
 content.replaceChildren(fragment);await loadCatalog();
 }catch{content.replaceChildren(node('p','Updates are temporarily unavailable. Please check back soon.','notice'),link(base+'/addons/page?slug='+site,'Open artist updates'),link('https://richrowmusic.com/contact.html','Booking & enquiries'));}}


// Public catalog access; database policies allow published records only.
const catalogBase='https://vajjwfxbbncqzrdbbvgu.supabase.co',publicKey='sb_publishable_Sg6NtRi3iJWIJEMzbViKvg_VZnvm-rg';
const normal=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
async function catalogRequest(path,options={}){const r=await fetch(catalogBase+path,{...options,headers:{apikey:publicKey,...options.headers},cache:'no-store'});if(!r.ok)throw Error('Catalog unavailable');return r.json();}
function youtube(url){try{const u=new URL(url);const id=u.hostname==='youtu.be'?u.pathname.slice(1):['youtube.com','www.youtube.com'].includes(u.hostname)?u.searchParams.get('v'):null;return /^[\w-]{11}$/.test(id||'')?'https://www.youtube-nocookie.com/embed/'+id:null;}catch{return null;}}
async function loadCatalog(){try{const query=new URLSearchParams({website_id:'eq.ebc7ea38-4b29-47ef-99f9-b454f0389e30',status:'eq.published',category:'in.(music,videos,releases)',select:'id,title,artist,category,description,link,cover_url,video_url',order:'display_order.asc,created_at.desc',limit:'200'});const all=await catalogRequest('/rest/v1/rr_content?'+query);const records=all.filter(r=>normal(r.artist||r.title).includes(site));
 for(const category of ['music','videos']){const target=document.getElementById(category);if(!target)continue;const rows=records.filter(r=>category==='music'?['music','releases'].includes(r.category):r.category==='videos');if(!rows.length)continue;for(const n of target.querySelectorAll('.block'))if(/^(New music and releases|Official videos) will appear here\.$/.test(n.textContent.trim()))n.remove();const grid=node('div',null,'catalog-grid');for(const r of rows){const card=node('article',null,'catalog-card');if(safe(r.cover_url)){const img=node('img');img.src=r.cover_url;img.alt=r.title+' cover';img.loading='lazy';card.append(img);}card.append(node('h3',r.title));if(r.description)card.append(node('p',r.description));const yt=youtube(r.video_url||r.link);if(yt&&category==='videos'){const frame=node('iframe');frame.src=yt;frame.title=r.title;frame.loading='lazy';frame.allow='fullscreen; picture-in-picture';frame.allowFullscreen=true;card.append(frame);}else if(safe(r.link)){card.append(link(r.link,yt?'Watch official video ↗':'Listen ↗'));}else if(category==='music'){const play=node('button','Listen to full song','action'),status=node('p');status.setAttribute('role','status');card.append(play,status);play.onclick=async()=>{play.disabled=true;try{const q=new URLSearchParams({content_id:'eq.'+r.id,select:'object_path'});const assets=await catalogRequest('/rest/v1/rr_audio_assets?'+q);if(!assets[0])throw Error();const signed=await catalogRequest('/storage/v1/object/sign/rr-audio-private/'+assets[0].object_path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!signed.signedURL)throw Error();const url=new URL(signed.signedURL.startsWith('/storage/v1/')?signed.signedURL:'/storage/v1/'+signed.signedURL.replace(/^\//,''),catalogBase);if(url.origin!==catalogBase)throw Error();const audio=node('audio');audio.controls=true;audio.preload='none';audio.src=url.href;card.querySelector('audio')?.remove();card.append(audio);status.textContent='Press play below. Free streaming.';play.textContent='Refresh player';}catch{status.textContent='Audio is temporarily unavailable. Please try again.';}finally{play.disabled=false;}};}grid.append(card);}target.append(grid);}
 }catch{/* Artist page content remains available if the shared catalog is offline. */}}

load();

import('./radio-player.js?v=cover3').then(({mountSpeakerRadio})=>{const root=document.createElement('section');document.querySelector('.hero').after(root);mountSpeakerRadio(root);}).catch(()=>{});
